# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :private_network, ip: "192.168.68.8"
  config.vm.provision "shell", path: "scripts/bootstrap.sh"
  config.vm.provision "shell", path: "scripts/wordpress.sh", privileged: false
  config.trigger.before :destroy do
   info "Dumping the database before destroying the VM..."
   run_remote  "rm -f /var/www/dist/wp-config.php && mysqldump --databases wordpress -u root > /vagrant/dev-database.sql"
  end
end
